name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
          # 清华源主地址（HTTPS）
          TUNA_SOURCE=" https://mirrors.tuna.tsinghua.edu.cn/ubuntu "
          CODENAME=$(lsb_release -cs)  # 获取 Ubuntu 代号（如 jammy/22.04）

          # 生成新的 sources.list 内容
          sudo tee /etc/apt/sources.list <<EOF
          # 清华大学开源软件镜像站（Ubuntu $CODENAME）
          deb ${TUNA_SOURCE}/ubuntu/ $CODENAME main restricted universe multiverse
          deb-src ${TUNA_SOURCE}/ubuntu/ $CODENAME main restricted universe multiverse

          deb ${TUNA_SOURCE}/ubuntu/ $CODENAME-updates main restricted universe multiverse
          deb-src ${TUNA_SOURCE}/ubuntu/ $CODENAME-updates main restricted universe multiverse

          deb ${TUNA_SOURCE}/ubuntu/ $CODENAME-backports main restricted universe multiverse
          deb-src ${TUNA_SOURCE}/ubuntu/ $CODENAME-backports main restricted universe multiverse

          deb ${TUNA_SOURCE}/ubuntu/ $CODENAME-security main restricted universe multiverse
          deb-src ${TUNA_SOURCE}/ubuntu/ $CODENAME-security main restricted universe multiverse
          EOF
  
          sudo apt-get update -y  # 若报错，说明源配置失败
          sudo apt install libc6-dev-i386 build-essential
          make test
