name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
          TUNA_SOURCE=" https://mirrors.tuna.tsinghua.edu.cn/ubuntu "
          CODENAME=$(lsb_release -cs)

          # 生成 sources.list（严格格式）
          sudo tee /etc/apt/sources.list <<'EOF'
          # 清华大学开源软件镜像站（Ubuntu）
          deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/  jammy main restricted universe multiverse
          deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/  jammy main restricted universe multiverse

          deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/  jammy-updates main restricted universe multiverse
          deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/  jammy-updates main restricted universe multiverse

          deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/  jammy-backports main restricted universe multiverse
          deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/  jammy-backports main restricted universe multiverse

          deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/  jammy-security main restricted universe multiverse
          deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/  jammy-security main restricted universe multiverse
          EOF

          # 强制使用 LF 换行符（避免 Windows 格式）
          sudo sed -i 's/\r$//' /etc/apt/sources.list
  
          sudo chmod 644 /etc/apt/sources.list
          sudo chmod 755 /etc/apt
          sudo apt-get update -y
          sudo apt-get install -y libc6-dev-i386 build-essential
          make test

    - name: Create Release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v1  # 推荐使用此 Action
      with:
        tag_name: ${{ github.ref_name }}  # 自动使用触发标签（如 v1.0.0）
        name: 'Release ${{ github.ref_name }}'  # Release 名称（可选）
        body_path: CHANGELOG.md  # 从文件读取变更日志
        files: test  # 上传 dist 目录下的所有文件作为附件
        draft: false  # 是否为草稿（false 表示直接发布）
        prerelease: false  # 是否为预发布（根据标签前缀判断，如 v1.0.0-rc1 设为 true）
