name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
            TUNA_MIRROR=" https://mirrors.tuna.tsinghua.edu.cn/ubuntu "  # 清华源主地址（HTTPS）
            sudo su
            cat << EOF > /etc/apt/sources.list
            # 清华大学开源软件镜像站（Ubuntu $codename）
            deb ${TUNA_MIRROR}/ubuntu/ $codename main restricted universe multiverse
            deb-src ${TUNA_MIRROR}/ubuntu/ $codename main restricted universe multiverse

            deb ${TUNA_MIRROR}/ubuntu/ $codename-updates main restricted universe multiverse
            deb-src ${TUNA_MIRROR}/ubuntu/ $codename-updates main restricted universe multiverse

            deb ${TUNA_MIRROR}/ubuntu/ $codename-backports main restricted universe multiverse
            deb-src ${TUNA_MIRROR}/ubuntu/ $codename-backports main restricted universe multiverse

            deb ${TUNA_MIRROR}/ubuntu/ $codename-security main restricted universe multiverse
            deb-src ${TUNA_MIRROR}/ubuntu/ $codename-security main restricted universe multiverse
            EOF
            sudo apt install libc6-dev-i386 build-essential
            make test
